// Generated by Dagger (https://dagger.dev).
package com.abramchuk.itbookstore.repository;

import com.abramchuk.itbookstore.ApiService;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class BookRepository_Factory implements Factory<BookRepository> {
  private final Provider<ApiService> apiServiceProvider;

  public BookRepository_Factory(Provider<ApiService> apiServiceProvider) {
    this.apiServiceProvider = apiServiceProvider;
  }

  @Override
  public BookRepository get() {
    return newInstance(apiServiceProvider.get());
  }

  public static BookRepository_Factory create(Provider<ApiService> apiServiceProvider) {
    return new BookRepository_Factory(apiServiceProvider);
  }

  public static BookRepository newInstance(ApiService apiService) {
    return new BookRepository(apiService);
  }
}
